

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Code style (check only)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-17
          files="$(git ls-files '*.h' '*.hpp' '*.c' '*.cc' '*.cpp' || true)"
          [ -n "$files" ] && clang-format-17 -style=file -n --Werror $files

      - name: Build gtest
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
      
      - name: Tests
        run: |
          make workflow_build_test
          ./bin/test

      
      - name: Speed test
        run: |
          make workflow_build_speed_test
          ./bin/speedtest
      
      
      



